Updates

diff --git a/aws-select-credentials b/aws-select-credentials
--- a/aws-select-credentials
+++ b/aws-select-credentials
@@ -9,9 +9,13 @@
 
 [ "${DEBUG:-0}" = "1" ] && set -x
 
+HOME="${HOME:-$(getent passwd $(id -u) | cut -d : -f 6)}"
+AWS_CREDENTIALS_FILE="${AWS_CREDENTIALS_FILE:-$HOME/.aws/credentials}"
+
 _cleanup () {
-    [ -n "$_TMP" ] && rm -rf "$_TMP"
-} ; trap _cleanup EXIT
+    [ -z "$_TMP" ] || rm -rf "$_TMP"
+}
+trap _cleanup EXIT
 
 _list_credentials () {
     local credname
@@ -28,7 +32,7 @@ _list_credentials () {
             aws_session_token*)
                     sessions[$credname]="$(printf "%s\n" "$line" | sed -e 's/^aws_session_token[[:blank:]]\+=[[:blank:]]*//g')" ;;
         esac
-    done < ~/.aws/credentials
+    done < "$AWS_CREDENTIALS_FILE"
 }
 
 _select_credential () {
@@ -62,17 +66,41 @@ _unset_credential () {
     echo "unset AWS_SELECTED_CREDENTIALS AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN"
 }
 
+_usage () {
+    cat <<EOUSAGE
+Usage: $0 [OPTIONS]
+
+Select some cached AWS credentials as environment variables. Useful if you have
+a dynamic credential provider for your AWS credentials and need to export the
+current values to another application (that may not be able to use your AWS
+profile configuration or read its files).
+
+Uses AWS_CREDENTIALS_FILE (~/.aws/credentials) to get cached credentials.
+
+Options:
+  -h                This screen
+  -u                Unset the environment variables
+  -f                Force mode
+EOUSAGE
+    exit 1
+}
+
 declare -a creds=()
 declare -A keys=() secrets=() sessions=()
+
 _list_credentials
 
 FORCE=0 UNSET=0
-while getopts "fu" args ; do
+while getopts "fuh" args ; do
     case "$args" in
+        h)
+                _usage ;;
         f)
                 FORCE=1 ;;
         u)
                 UNSET=1 ;;
+        *)
+                echo "$0: Error: invalid args '$args'" ; exit 1 ;;
     esac
 done
 shift $((OPTIND-1))
